"use client";

import { FormEvent, useEffect, useState } from "react";
import { API_URL } from "../lib/api";

export default function SettingsPage() {
  const [workspaceId, setWorkspaceId] = useState("");
  const [form, setForm] = useState({ name: "", companyName: "", brandColor: "#ff7548", logoUrl: "", defaultCity: "Karachi", customDomain: "" });
  const [message, setMessage] = useState("Loading settings...");
  useEffect(() => { fetch(`${API_URL}/api/workspaces`, { credentials: "include" }).then(r => r.json()).then(x => { const w = x.items?.[0]; if (!w) { setMessage(x.error?.message ?? "Sign in to edit settings."); return; } setWorkspaceId(w.id); setForm({ name: w.name ?? "", companyName: w.companyName ?? "", brandColor: w.brandColor ?? "#ff7548", logoUrl: w.logoUrl ?? "", defaultCity: w.defaultCity ?? "Karachi", customDomain: w.customDomain ?? "" }); setMessage(""); }).catch(() => setMessage("Settings could not be loaded.")); }, []);
  async function save(event: FormEvent) { event.preventDefault(); const r = await fetch(`${API_URL}/api/workspaces/${workspaceId}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const x = await r.json(); setMessage(r.ok ? "Workspace settings saved." : x.error?.message ?? "Settings could not be saved."); }
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  return <main className="section-page"><header className="page-heading"><div><p className="eyebrow">Workspace settings</p><h1>Make LeadPitch yours.</h1><p className="muted">Brand shared pitches and set defaults for your team.</p></div></header><form onSubmit={save}><div className="settings-grid"><section className="panel settings-card"><h2>Brand identity</h2><label>Workspace name<input value={form.name} onChange={e => update("name", e.target.value)} required /></label><label>Company name<input value={form.companyName} onChange={e => update("companyName", e.target.value)} /></label><label>Share-link color<input type="color" value={form.brandColor} onChange={e => update("brandColor", e.target.value)} /></label><label>Logo URL<input value={form.logoUrl} onChange={e => update("logoUrl", e.target.value)} placeholder="https://..." /></label></section><section className="panel settings-card"><h2>Workspace defaults</h2><label>Default city<select value={form.defaultCity} onChange={e => update("defaultCity", e.target.value)}>{["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Peshawar", "Multan"].map(city => <option key={city}>{city}</option>)}</select></label><label>Custom share domain<input value={form.customDomain} onChange={e => update("customDomain", e.target.value)} placeholder="offers.example.com" /></label><label>Currency<input value="PKR" readOnly /></label></section></div><button className="primary-action" type="submit" disabled={!workspaceId}>Save changes</button>{message && <p className="notice" role="status">{message}</p>}</form></main>;
}
