"use client";

import { FormEvent, useEffect, useState } from "react";
import { API_URL } from "../lib/api";
type Key = { id: string; name: string; prefix: string; scopes: string[]; revoked: boolean };
type Hook = { id: string; url: string; events: string[]; active: boolean };
const EVENTS = ["lead.discovered", "website.classified", "audit.completed", "pitch.viewed", "pipeline.stage_changed", "prototype.export_completed"];
export default function DeveloperPage() {
  const [keys, setKeys] = useState<Key[]>([]); const [hooks, setHooks] = useState<Hook[]>([]); const [url, setUrl] = useState(""); const [message, setMessage] = useState("");
  async function load() { const [kr, wr] = await Promise.all([fetch(`${API_URL}/api/api-keys`, { credentials: "include" }), fetch(`${API_URL}/api/webhooks`, { credentials: "include" })]); const k = await kr.json(); const w = await wr.json(); setKeys(k.items ?? []); setHooks(w.items ?? []); if (!kr.ok) setMessage(k.error?.message ?? "Sign in to manage developer settings."); }
  useEffect(() => { void load(); }, []);
  async function createKey() { const r = await fetch(`${API_URL}/api/api-keys`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Local development key", scopes: ["leads:read", "audits:read"] }) }); const x = await r.json(); setMessage(r.ok ? `Copy this key now — it is shown once: ${x.key}` : x.error?.message ?? "Key creation failed."); void load(); }
  async function addWebhook(event: FormEvent) { event.preventDefault(); const r = await fetch(`${API_URL}/api/webhooks`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url, events: ["lead.discovered", "audit.completed", "pipeline.stage_changed"] }) }); const x = await r.json(); setMessage(r.ok ? `Webhook created. Save this secret now: ${x.secret}` : x.error?.message ?? "Webhook creation failed."); if (r.ok) setUrl(""); void load(); }
  async function remove(path: string) { await fetch(`${API_URL}${path}`, { method: "DELETE", credentials: "include" }); void load(); }
  return <main className="section-page"><header className="page-heading"><div><p className="eyebrow">Developer tools</p><h1>Connect your workflow.</h1><p className="muted">Secrets are displayed only once. Store them securely.</p></div><a className="secondary-action" href={`${API_URL}/openapi.json`} target="_blank" rel="noreferrer">Open API docs</a></header><div className="settings-grid"><section className="panel settings-card"><h2>API keys</h2><button className="primary-action" onClick={() => void createKey()}>Create read-only key</button>{keys.map(key => <div className="list-row" key={key.id}><span><strong>{key.name}</strong><small>{key.prefix} · {key.scopes.join(", ")}</small></span>{key.revoked ? <span className="muted">Revoked</span> : <button className="text-button" onClick={() => void remove(`/api/api-keys/${key.id}`)}>Revoke</button>}</div>)}</section><section className="panel settings-card"><h2>Webhooks</h2><form onSubmit={addWebhook} className="inline-form"><input type="url" required placeholder="https://example.com/leadpitch" value={url} onChange={e => setUrl(e.target.value)} /><button className="secondary-action">Add webhook</button></form>{hooks.map(hook => <div className="list-row" key={hook.id}><span><strong>{hook.url}</strong><small>{hook.events.join(", ")}</small></span><button className="text-button" onClick={() => void remove(`/api/webhooks/${hook.id}`)}>Delete</button></div>)}<small className="muted">Supported events: {EVENTS.join(", ")}</small></section></div>{message && <p className="notice" role="status">{message}</p>}</main>;
}
